# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # https://github.com/VirtualBox/virtualbox/issues/188
  boot.extraModprobeConfig = "options kvm enable_virt_at_load=0";

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd:1"];
  };

  fileSystems."/home/hana/btrfs" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["compress=zstd:1"];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/f1f349a7-5b8e-48fe-a497-f8cbdd31e8a8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1041-88A8";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/af434983-cf64-4040-8eb5-7123aaceb55e";}
  ];

  zramSwap = {
    enable = true;
    priority = 100;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
